package edu.grinnell.grinnell_publications_android.Services.Templates;

import com.google.gson.annotations.Expose;
import com.google.gson.annotations.SerializedName;

/**
 *  This class is a json template that the Call block populates when an author item is retrieved
 *      from AWS endpoint
 *
 *  @author Dennis Chan, generated by www.jsonschema2pojo.org
 *  @since  February 26, 2017
 *  @see    JsonStory
 *  @see    JsonAuthor
 *  @see    PublicationRemoteClient
 */

public class JsonPublication {

    @SerializedName("id")
    @Expose
    private String mId;
    @SerializedName("name")
    @Expose
    private String mName;

    public String getId() {
        return mId;
    }

    public void setId(String id) {
        this.mId = id;
    }

    public String getName() {
        return mName;
    }

    public void setName(String name) {
        this.mName = name;
    }

}